/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Test Runner Used To Run Each Test Below=====*/
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include "../dichotomicKeyboard.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_1_symbol_dichotomic_keyboard_should_always_give_same_letter(void);
extern void test_2_symbols_dichotomic_keyboard_should_navigate_to_right(void);
extern void test_2_symbols_dichotomic_keyboard_should_navigate_to_left(void);
extern void test_3_symbols_dichotomic_keyboard_should_navigate_to_right(void);
extern void test_3_symbols_dichotomic_keyboard_should_navigate_to_left(void);
extern void test_4_symbols_dichotomic_keyboard_should_navigate_to_right(void);
extern void test_dichotomic_keyboard_should_navigate_to_right_or_left(void);


/*=======Test Reset Option=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  setUp();
}


/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test/TestDichotomicKeyboard.c");
  RUN_TEST(test_1_symbol_dichotomic_keyboard_should_always_give_same_letter, 13);
  RUN_TEST(test_2_symbols_dichotomic_keyboard_should_navigate_to_right, 36);
  RUN_TEST(test_2_symbols_dichotomic_keyboard_should_navigate_to_left, 54);
  RUN_TEST(test_3_symbols_dichotomic_keyboard_should_navigate_to_right, 71);
  RUN_TEST(test_3_symbols_dichotomic_keyboard_should_navigate_to_left, 89);
  RUN_TEST(test_4_symbols_dichotomic_keyboard_should_navigate_to_right, 107);
  RUN_TEST(test_dichotomic_keyboard_should_navigate_to_right_or_left, 127);

  return (UnityEnd());
}
